import 'server-only'
import { SignJWT, jwtVerify } from 'jose'

/**
 * The token that tells a payment callback WHICH STORE it belongs to.
 *
 * ── THE PROBLEM IT SOLVES ────────────────────────────────────────────────
 *
 * Verifying a PayFast callback needs that store's passphrase. So the store has
 * to be known BEFORE verification can run — which means the store cannot be
 * established BY verifying. Something in the request must name it first, and
 * whatever names it must not be forgeable into pointing at a different store,
 * and must not leak the tenant id.
 *
 * ── WHY NOT A RAW siteId IN THE URL ──────────────────────────────────────
 *
 * It is an enumerable tenant identifier: change the 1 to a 2 and you are
 * aiming a payment callback at someone else's shop.
 *
 * ── WHY NOT THE REFERENCE ALONE ──────────────────────────────────────────
 *
 * Intents live in each store's OWN database. With only a reference we would
 * have to search every store's database to find the callback's owner —
 * unbounded work, driven by an unauthenticated request, which is a denial of
 * service waiting to happen.
 *
 * ── SO ───────────────────────────────────────────────────────────────────
 *
 * The notify URL carries an opaque token binding siteId AND reference
 * together, minted when the intent is created. Binding both is what matters: a
 * token for store A cannot be replayed against store B's payment, because the
 * reference inside it would not match that store's row.
 *
 * This is IDENTIFICATION, NEVER AUTHORISATION. A valid token gets a callback
 * as far as "which store, which intent". The payload must still pass the full
 * signature, source-IP, post-back, merchant and amount checks before a cent is
 * considered received.
 *
 * ── THE JWT IS TOO LONG FOR A notify_url ─────────────────────────────────
 *
 * MEASURED: the signed token is 246 characters, which puts a notify URL at 296
 * — and PayFast documents a 255-character limit on that field. It accepts the
 * checkout form anyway and then simply never posts the callback, so the payment
 * succeeds, the money moves, and nothing on our side ever hears about it. The
 * shop sees "Confirming your payment" for ever.
 *
 * `callbackPath` below is the replacement, and it keeps every property the
 * paragraphs above demand:
 *
 *   the store is named FIRST, so no database fan-out;
 *   the site id is base36 rather than a bare integer, so it is not a decimal
 *     tenant id anybody would think to increment;
 *   the REFERENCE is the unguessable half — 144 bits from a CSPRNG, unique by
 *     database constraint, and generated by us. A forged one matches no row.
 *
 * What is lost is the signature over the pair and the 24-hour expiry. Neither
 * was doing the work: a caller who cannot guess the reference cannot forge a
 * pairing either, and the intent's own `status = 'pending'` guard is what stops
 * a replay — not the token's lifetime. Everything the callback then does is
 * still gated on the full four-step verification.
 *
 * `createCallbackToken`/`readCallbackToken` stay for the /pay/[token] page,
 * which is a different job: that link goes in an EMAIL, where length costs
 * nothing and a 24-hour expiry is exactly what a mailed link should have.
 */

/**
 * The path segment a payment callback is addressed by. Short, by necessity.
 *
 * Deliberately NOT a token: see the note above. Symmetrical with the printed
 * pay code (`lib/site/payLinks.ts`), which solved the same length problem the
 * same way, so there is one shape to recognise rather than two.
 */
export function callbackPath(siteId: number, reference: string): string {
  return `${siteId.toString(36)}-${reference}`
}

/**
 * Split a callback path back into the store and the payment it names.
 *
 * Null for anything malformed. The caller turns every null into the same silent
 * acknowledgement, so this cannot be used to probe which references exist.
 */
export function readCallbackPath(
  path: string,
): { siteId: number; reference: string } | null {
  const at = path.indexOf('-')
  if (at <= 0) return null

  const reference = path.slice(at + 1)

  /*
   * ── THE PREFIX MUST LOOK LIKE A SITE ID, NOT MERELY PARSE AS ONE ────────
   *
   * A JWT begins `eyJhbGciOiJIUzI1NiJ9.eyJzaXRlS…` and contains a '-' deep in
   * its payload, so a naive split parsed one into siteId 5.55e+30 — and
   * `Number.isInteger` says TRUE for that, because it is a whole float. The
   * guard passed, this function claimed the JWT, and the fallback that exists
   * to honour PayFast's retry queue never ran. A real payment's retried
   * callback would have been silently dropped.
   *
   * Two bounds close it: the prefix is at most 8 base36 digits (well past any
   * plausible site count, and far short of a JWT header), and the result must
   * be a SAFE integer inside that range.
   */
  const prefix = path.slice(0, at)
  if (!/^[0-9a-z]{1,8}$/.test(prefix)) return null

  const siteId = parseInt(prefix, 36)
  if (!Number.isSafeInteger(siteId) || siteId <= 0) return null

  // Our own references start ODY- and are ~28 chars; the cap is a sanity bound
  // on what reaches a database query, not a format assertion.
  if (!reference || reference.length > 64) return null

  return { siteId, reference }
}

const AUDIENCE = 'ody-payment-callback'

function secret(): Uint8Array {
  const raw = process.env.SESSION_SECRET
  if (!raw) throw new Error('SESSION_SECRET is not configured.')
  return new TextEncoder().encode(raw)
}

export async function createCallbackToken(siteId: number, reference: string): Promise<string> {
  return new SignJWT({ siteId, reference })
    .setProtectedHeader({ alg: 'HS256' })
    .setAudience(AUDIENCE)
    .setIssuedAt()
    // A payment attempt that has not been settled within a day is dead. The
    // gateway retries for far less than that, so this costs nothing real while
    // closing the window on a leaked notify URL.
    .setExpirationTime('24h')
    .sign(secret())
}

export async function readCallbackToken(
  token: string,
): Promise<{ siteId: number; reference: string } | null> {
  try {
    const { payload } = await jwtVerify(token, secret(), { audience: AUDIENCE })
    const siteId = Number(payload.siteId)
    const reference = typeof payload.reference === 'string' ? payload.reference : ''
    if (!Number.isInteger(siteId) || siteId <= 0 || !reference) return null
    return { siteId, reference }
  } catch {
    return null
  }
}
