import type { ProductTypeId } from '../productTypes'

/**
 * The shapes the till and the server both speak.
 *
 * No `server-only`, no `'use client'`, no imports beyond a type — so the browser
 * half and the route half read the SAME definition. Two copies of a sync payload
 * is how a field gets added on one side and silently ignored on the other, which
 * with money in it is the worst kind of drift.
 */

/* ── A sale rung up offline ──────────────────────────────────────────────── */

export type OfflineSaleLine = {
  productId: number | null
  productCode: string | null
  description: string
  productType: ProductTypeId
  departmentId: number | null
  qty: number
  unitPriceIncl: number
  /** The EFFECTIVE discount — what the slip showed, after the special comparison. */
  discountPct: number
  /** Which special caused it, so a promotion's cost can be reported on. */
  specialId: number | null
  vatRatePct: number
  unitCostExcl: number
}

export type OfflineTender = {
  tenderTypeId: number
  /** For the error message when the id has since been deleted. */
  tenderCode: string
  /** What was HANDED OVER, gross — never the amount owed. */
  amount: number
  reference: string | null
}

export type OfflineSale = {
  /** UUIDv4, generated by the till. THE idempotency key. */
  saleUid: string
  /**
   * The number already PRINTED on the customer's slip.
   *
   * Not a request — the customer is holding it. The server adopts it and moves the
   * till's sequence past it rather than allocating a second one.
   */
  documentNumber: string
  terminalId: number | null
  terminalCode: string | null
  /** Attribution only. The server re-derives this person's capabilities. */
  operatorUserId: number
  operatorName: string
  /** The shift that took the cash, when the till knew it. */
  shiftId: number | null
  /** When the money changed hands, from the till's own clock. ISO. */
  takenAt: string
  /** YYYY-MM-DD. Governs the VAT period. */
  documentDate: string
  priceStructureId: number | null
  customerId: number | null
  customerName: string | null
  customerVatNo: string | null
  customerPhone: string | null
  lines: OfflineSaleLine[]
  tenders: OfflineTender[]
  /**
   * What the till CHARGED.
   *
   * Compared against the server's own recomputation, never trusted in place of
   * it. A mismatch is recorded on the document as an exception; the server's
   * figure is what posts. See postOfflineSale.
   */
  claimedTotalIncl: number
  claimedTenderedTotal: number
  claimedChange: number
}

/* ── One request ─────────────────────────────────────────────────────────── */

export type SyncRequest = {
  deviceId: string
  /** Oldest first, and at most BATCH_SIZE. */
  sales: OfflineSale[]
}

export type SyncSaleResult = {
  saleUid: string
  ok: boolean
  /** Present whenever the sale is on the books — INCLUDING on a replay. */
  documentNumber?: string
  documentId?: number
  /** Why a manager should look at it. Null for the overwhelming majority. */
  exception?: string | null
  /** True when this uid was already posted. The till prunes and moves on. */
  duplicate?: boolean
  error?: string
  /**
   * Whether the till should keep this entry and try again.
   *
   * False for a structural rejection: retrying a malformed sale forever is a queue
   * that never drains and a cashier who never finds out.
   */
  retryable?: boolean
}

export type SyncResponse = {
  results: SyncSaleResult[]
  /** One per cancellation sent, so the till knows which reached the audit trail. */
  cancelled?: { saleUid: string; ok: boolean; error?: string }[]
}

/* ── What the till holds locally ─────────────────────────────────────────── */

/**
 * An outbox entry's life.
 *
 * `failed` needs a human; `pending` and `synced` are the machine's. `cancelled` is
 * the odd one: the sale is NOT going to be posted, but the row still has to reach the
 * server — a till that can make a sale disappear without a trace is a till somebody
 * can steal from. See `offline_cancelled_sales`.
 */
export type OutboxStatus = 'pending' | 'synced' | 'failed' | 'cancelled'

export type OutboxSale = OfflineSale & {
  status: OutboxStatus
  /** How many times sync has tried. Read by the outbox screen, not by policy. */
  attempts: number
  lastError: string | null
  /** Set once the server has it. */
  syncedAt: string | null
  /** Why a cashier cancelled it, and when. Both null unless `status` is cancelled. */
  cancelReason?: string | null
  cancelledAt?: string | null
  /**
   * Who cancelled it — recorded ALONGSIDE `operatorUserId`, never over it.
   *
   * "Who rang this up" and "who made it disappear" are different questions, and a shop
   * looking into a pattern of cancelled sales needs both. Overwriting the first would
   * hide exactly the case this trail exists to catch.
   */
  cancelledByUserId?: number | null
  cancelledByName?: string | null
  /**
   * Whether the number this sale consumed was BURNT rather than handed back.
   *
   * True in almost every case, and the exception is narrow: only a sale cancelled
   * while it was still the most recently issued counter, with nothing printed since,
   * can rewind. Anything else must burn — the customer may be holding a slip with
   * that number on it, and reissuing it would put two different sales under one
   * invoice number with no unique index offline to catch it.
   *
   * Recorded rather than inferred because it is the explanation for the one gap a
   * till's otherwise gapless run can have, and `verifySequence` reads it the same way
   * it reads a cancelled document that kept its number.
   */
  numberBurnt?: boolean
}

/** A cancelled offline sale, on its way to the audit trail. */
export type CancelledSale = {
  saleUid: string
  documentNumber: string
  terminalId: number | null
  terminalCode: string | null
  operatorUserId: number
  operatorName: string
  totalIncl: number
  reason: string
  takenAt: string
  cancelledAt: string
  /** Every line and tender, so a pattern of large cancellations is visible. */
  payload: unknown
}

/** What the header chip shows, and what the cashier needs before going home. */
export type PosSyncState = {
  online: boolean
  syncing: boolean
  /** Waiting to go. THE figure a cashier must see before closing up. */
  pending: number
  /** Refused for a reason a human has to act on. */
  failed: number
  lastSyncAt: string | null
  lastError: string | null
}
