import type { ProductTypeId } from '../productTypes'
import type { ChosenOption } from '../instructionRules'

/**
 * The shapes the till and the server both speak.
 *
 * No `server-only`, no `'use client'`, no imports beyond a type — so the browser
 * half and the route half read the SAME definition. Two copies of a sync payload
 * is how a field gets added on one side and silently ignored on the other, which
 * with money in it is the worst kind of drift.
 */

/* ── A sale rung up offline ──────────────────────────────────────────────── */

export type OfflineSaleLine = {
  productId: number | null
  productCode: string | null
  description: string
  productType: ProductTypeId
  departmentId: number | null
  qty: number
  unitPriceIncl: number
  /** The EFFECTIVE discount — what the slip showed, after the special comparison. */
  discountPct: number
  /** Which special caused it, so a promotion's cost can be reported on. */
  specialId: number | null
  vatRatePct: number
  unitCostExcl: number
  /**
   * The answers given to this product's questions, and any note.
   *
   * OPTIONAL, and that is load-bearing: a sale queued in the outbox before this
   * shipped has neither field, and it must still post. The outbox is the one
   * store in this app whose rows cannot be recreated — a till that refused them
   * would be losing sales that already happened. See `linesFor`.
   *
   * The answers' price is already inside `unitPriceIncl`; these travel so the
   * invoice can record WHAT was chosen, not to be charged again.
   */
  instructions?: ChosenOption[]
  note?: string
}

export type OfflineTender = {
  tenderTypeId: number
  /** For the error message when the id has since been deleted. */
  tenderCode: string
  /** What was HANDED OVER, gross — never the amount owed. */
  amount: number
  reference: string | null
}

export type OfflineSale = {
  /** UUIDv4, generated by the till. THE idempotency key. */
  saleUid: string
  /**
   * The number already PRINTED on the customer's slip.
   *
   * Not a request — the customer is holding it. The server adopts it and moves the
   * till's sequence past it rather than allocating a second one.
   */
  documentNumber: string
  terminalId: number | null
  terminalCode: string | null
  /** Attribution only. The server re-derives this person's capabilities. */
  operatorUserId: number
  operatorName: string
  /** The shift that took the cash, when the till knew it. */
  shiftId: number | null
  /** When the money changed hands, from the till's own clock. ISO. */
  takenAt: string
  /** YYYY-MM-DD. Governs the VAT period. */
  documentDate: string
  priceStructureId: number | null
  customerId: number | null
  customerName: string | null
  customerVatNo: string | null
  customerPhone: string | null
  lines: OfflineSaleLine[]
  tenders: OfflineTender[]
  /**
   * What the till CHARGED.
   *
   * Compared against the server's own recomputation, never trusted in place of
   * it. A mismatch is recorded on the document as an exception; the server's
   * figure is what posts. See postOfflineSale.
   */
  claimedTotalIncl: number
  claimedTenderedTotal: number
  claimedChange: number
  /**
   * Tips a cashier DECLARED at the pad, keyed by tender type id.
   *
   * OPTIONAL, and that is load-bearing for the same reason `instructions` is: a sale queued
   * before this shipped has no such field and must still post. The outbox is the one store
   * whose rows cannot be recreated.
   *
   * Undefined means "no tips", which is exactly the behaviour before tips existed — so an
   * old queued sale posts identically.
   */
  declaredTips?: Record<number, number>
  /**
   * The forced service charge the slip showed, or absent.
   *
   * Carried rather than recomputed at sync, because the TIERS may have changed by the time
   * the till reconnects — a shop that edited its bands at 18:00 must not have that reprice a
   * bill a customer settled at 17:30. The figure on the slip is the figure that posts.
   */
  serviceCharge?: number
  /**
   * Supervisor authorisations given at the till while offline.
   *
   * OPTIONAL like `declaredTips`, for the same reason: old queued sales must
   * still post. The identity here was verified against the stored PBKDF2
   * verifiers at the counter, but the stored capability list is only as fresh
   * as the last catalog — so the server RE-DERIVES each authoriser's right at
   * sync (an offline sale always posts; a claim that fails re-derivation
   * becomes an exception on the document, not a refusal).
   */
  overrides?: {
    capability: string
    userId: number
    name: string
    /** What was authorised, in words: "25% discount on Bread". */
    action: string
    amount?: number
  }[]
}

/* ── One request ─────────────────────────────────────────────────────────── */

export type SyncRequest = {
  deviceId: string
  /** Oldest first, and at most BATCH_SIZE. */
  sales: OfflineSale[]
  /**
   * Returns taken offline. Posted AFTER sales, deliberately.
   *
   * A return and a sale are independent documents, so strictly the order does not
   * affect either one's arithmetic. It affects the STOCK: a sale that drove a product
   * negative and a return that puts it back read far more sensibly in the movement
   * ledger in the order they happened, and a shop reading `stock_movements` to find out
   * why a count is wrong should not have to reason about sync order to do it.
   *
   * Cancellations still come last, after both — see the sync route.
   */
  returns?: OfflineReturn[]
}

export type SyncSaleResult = {
  saleUid: string
  ok: boolean
  /** Present whenever the sale is on the books — INCLUDING on a replay. */
  documentNumber?: string
  documentId?: number
  /** Why a manager should look at it. Null for the overwhelming majority. */
  exception?: string | null
  /** True when this uid was already posted. The till prunes and moves on. */
  duplicate?: boolean
  error?: string
  /**
   * Whether the till should keep this entry and try again.
   *
   * False for a structural rejection: retrying a malformed sale forever is a queue
   * that never drains and a cashier who never finds out.
   */
  retryable?: boolean
}

export type SyncResponse = {
  results: SyncSaleResult[]
  /** One per return sent, in the same shape and with the same retry contract. */
  returns?: SyncReturnResult[]
  /** One per cancellation sent, so the till knows which reached the audit trail. */
  cancelled?: { saleUid: string; ok: boolean; error?: string }[]
}

/* ── What the till holds locally ─────────────────────────────────────────── */

/**
 * An outbox entry's life.
 *
 * `failed` needs a human; `pending` and `synced` are the machine's. `cancelled` is
 * the odd one: the sale is NOT going to be posted, but the row still has to reach the
 * server — a till that can make a sale disappear without a trace is a till somebody
 * can steal from. See `offline_cancelled_sales`.
 */
export type OutboxStatus = 'pending' | 'synced' | 'failed' | 'cancelled'

export type OutboxSale = OfflineSale & {
  status: OutboxStatus
  /** How many times sync has tried. Read by the outbox screen, not by policy. */
  attempts: number
  lastError: string | null
  /** Set once the server has it. */
  syncedAt: string | null
  /** Why a cashier cancelled it, and when. Both null unless `status` is cancelled. */
  cancelReason?: string | null
  cancelledAt?: string | null
  /**
   * Who cancelled it — recorded ALONGSIDE `operatorUserId`, never over it.
   *
   * "Who rang this up" and "who made it disappear" are different questions, and a shop
   * looking into a pattern of cancelled sales needs both. Overwriting the first would
   * hide exactly the case this trail exists to catch.
   */
  cancelledByUserId?: number | null
  cancelledByName?: string | null
  /**
   * Whether the number this sale consumed was BURNT rather than handed back.
   *
   * True in almost every case, and the exception is narrow: only a sale cancelled
   * while it was still the most recently issued counter, with nothing printed since,
   * can rewind. Anything else must burn — the customer may be holding a slip with
   * that number on it, and reissuing it would put two different sales under one
   * invoice number with no unique index offline to catch it.
   *
   * Recorded rather than inferred because it is the explanation for the one gap a
   * till's otherwise gapless run can have, and `verifySequence` reads it the same way
   * it reads a cancelled document that kept its number.
   */
  numberBurnt?: boolean
}

/* ── A return taken offline ──────────────────────────────────────────────── */

/**
 * One line of a return taken while the till could not reach the server.
 *
 * `unitCostExcl` is carried rather than looked up, for the same reason the online
 * credit note copies it from the original invoice line: re-reading the product's cost
 * at sync time would value a return at TODAY's cost and manufacture margin that was
 * never earned. Offline the till has only its catalog's copy, which is the closest
 * honest answer available and is recorded as what it used.
 */
export type OfflineReturnLine = {
  productId: number | null
  productCode: string | null
  description: string
  productType: ProductTypeId
  departmentId: number | null
  /** POSITIVE here. The server stores it negative — see createCreditNote. */
  qty: number
  unitPriceIncl: number
  vatRatePct: number
  unitCostExcl: number
}

/**
 * A return rung up offline.
 *
 * ── WHY THERE IS NO invoiceId ─────────────────────────────────────────────
 *
 * This is a RETURN WITHOUT A RECEIPT — `createCreditNote`'s `invoiceId: null` case,
 * which already exists and is already a first-class path.
 *
 * A receipted return deliberately is NOT supported offline, and the reason is a guard
 * the till structurally cannot run: `creditedQtyByLine` sums every credit note ever
 * raised against that invoice, across every till and the back office, to refuse
 * crediting more than was sold. A till knows only about its own sales. Two tills, or a
 * return against a sale from last week, and an offline receipted return would credit
 * one invoice twice with nothing able to notice — and a credit note is money going out
 * of the drawer.
 *
 * So the till takes the return as a no-receipt return, which reverses nothing in
 * particular and therefore has no over-credit guard to miss. That is a real
 * limitation, not a disguised one: the slip says "return without a receipt" and a
 * manager can see on the exceptions screen that it was taken blind.
 */
export type OfflineReturn = {
  /** UUIDv4 from the till. THE idempotency key, same contract as a sale's. */
  returnUid: string
  /**
   * The number the credit note was printed under.
   *
   * Same rule as a sale: the customer is holding it, so the server adopts it rather
   * than allocating a second one. Drawn from the till's OWN credit-note sequence, not
   * the invoice one — two documents under one number is the thing uq_doc_number exists
   * to stop, and offline there is no index to catch it.
   */
  documentNumber: string
  terminalId: number | null
  terminalCode: string | null
  operatorUserId: number
  operatorName: string
  /** Who authorised it, when the operator did not hold `sales.credit_note`. */
  authorisedByUserId: number | null
  authorisedByName: string | null
  shiftId: number | null
  takenAt: string
  documentDate: string
  customerId: number | null
  customerName: string | null
  /**
   * Which of the shop's return reasons this is. Required — `createCreditNote`
   * refuses a missing one, and so does the till.
   *
   * The ID is carried rather than the code, because the row it points at cannot
   * change under it: a retired reason still resolves, and a renamed one syncs
   * under its new name. What CAN happen is the row being deleted outright
   * before this syncs, which `requireSalesReason` turns into a stated refusal
   * rather than a silently reason-less credit note.
   */
  reasonId: number
  /** The optional free-text detail beside the code. */
  note: string | null
  lines: OfflineReturnLine[]
  /** What went back out of the drawer. Empty leaves the credit on the account. */
  refunds: OfflineTender[]
  /** What the till computed, for the same comparison a sale gets. */
  claimedTotalIncl: number
  claimedRefundTotal: number
}

export type OutboxReturn = OfflineReturn & {
  status: OutboxStatus
  attempts: number
  lastError: string | null
  syncedAt: string | null
  cancelReason?: string | null
  cancelledAt?: string | null
  cancelledByUserId?: number | null
  cancelledByName?: string | null
  numberBurnt?: boolean
}

export type SyncReturnResult = {
  returnUid: string
  ok: boolean
  documentNumber?: string
  documentId?: number
  exception?: string | null
  duplicate?: boolean
  error?: string
  retryable?: boolean
}

/** A cancelled offline sale, on its way to the audit trail. */
export type CancelledSale = {
  saleUid: string
  documentNumber: string
  terminalId: number | null
  terminalCode: string | null
  operatorUserId: number
  operatorName: string
  totalIncl: number
  reason: string
  takenAt: string
  cancelledAt: string
  /** Every line and tender, so a pattern of large cancellations is visible. */
  payload: unknown
}

/** What the header chip shows, and what the cashier needs before going home. */
export type PosSyncState = {
  online: boolean
  syncing: boolean
  /** Waiting to go. THE figure a cashier must see before closing up. */
  pending: number
  /** Refused for a reason a human has to act on. */
  failed: number
  lastSyncAt: string | null
  lastError: string | null
}
